name: vvims
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  flutter_expandable_fab: ^2.0.0
  flutter_speed_dial: ^7.0.0
  camera: ^0.10.5+9
  provider: ^6.1.2
  connectivity_plus: ^6.0.2
  shared_preferences: ^2.2.3
  fluttertoast: ^8.2.5
  google_mlkit_text_recognition: ^0.11.0
  change_app_package_name: ^1.1.0
  image_picker: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/font/

fonts:
    - family: Sk-Modernist
      fonts:
        - asset: assets/fonts/Sk-Modernist.otf

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat.ttf
